import crypto from "crypto";
import { google } from "googleapis";
import { updateGoogleAccessToken } from "../../repository/user.repository.js";

export const GOOGLE_OAUTH_SCOPES = [
  "openid",
  "https://www.googleapis.com/auth/userinfo.email",
  "https://www.googleapis.com/auth/userinfo.profile",
  "https://www.googleapis.com/auth/spreadsheets",
  "https://www.googleapis.com/auth/drive.file",
];

/**
 * Generates the Google OAuth authorization URL and CSRF/Shop state cookies.
 */
export function generateGoogleOAuthUrlAndHeaders(shop) {
  const state = crypto.randomUUID();
  const rootUrl = "https://accounts.google.com/o/oauth2/v2/auth";
  const options = {
    redirect_uri: process.env.GOOGLE_REDIRECT_URI,
    client_id: process.env.GOOGLE_CLIENT_ID,
    access_type: "offline",
    response_type: "code",
    prompt: "consent",
    scope: GOOGLE_OAUTH_SCOPES.join(" "),
    state,
  };
  const qs = new URLSearchParams(options).toString();
  const googleOauthUrl = `${rootUrl}?${qs}`;

  const headers = new Headers();
  headers.append(
    "Set-Cookie",
    `oauth_state=${state}; Path=/; HttpOnly; Secure; SameSite=None; Max-Age=3600`
  );
  headers.append(
    "Set-Cookie",
    `oauth_shop=${shop}; Path=/; HttpOnly; Secure; SameSite=None; Max-Age=3600`
  );

  return { googleOauthUrl, headers };
}

/**
 * Returns an authenticated Google OAuth2 client for the given GoogleAccount record.
 * Automatically handles token refresh via getAccessToken and updates database on 'tokens' event.
 */
export async function getAuthenticatedOAuthClient(googleAccount) {
  if (!googleAccount) {
    throw new Error("Google account record is required for authentication");
  }

  const oauth2Client = new google.auth.OAuth2(
    process.env.GOOGLE_CLIENT_ID,
    process.env.GOOGLE_CLIENT_SECRET,
    process.env.GOOGLE_REDIRECT_URI
  );

  oauth2Client.setCredentials({
    access_token: googleAccount.accessToken,
    refresh_token: googleAccount.refreshToken,
    expiry_date: googleAccount.accessTokenExpiresAt
      ? new Date(googleAccount.accessTokenExpiresAt).getTime()
      : undefined,
  });

  // Automatically persist any refreshed credentials generated by googleapis
  oauth2Client.on("tokens", async (credentials) => {
    try {
      await updateGoogleAccessToken({
        googleAccountId: googleAccount.id,
        accessToken: credentials.access_token,
        expiresIn: credentials.expiry_date
          ? Math.floor((credentials.expiry_date - Date.now()) / 1000)
          : 3600,
        refreshToken: credentials.refresh_token,
      });
    } catch (err) {
      console.warn("Failed to persist refreshed Google tokens:", err.message);
    }
  });

  // Pre-emptively refresh if token is within 5 minutes of expiring
  const isExpiring =
    googleAccount.accessTokenExpiresAt &&
    new Date(googleAccount.accessTokenExpiresAt).getTime() - Date.now() < 5 * 60 * 1000;

  if (isExpiring && googleAccount.refreshToken) {
    try {
      const { token } = await oauth2Client.getAccessToken();
      if (token) {
        oauth2Client.setCredentials({ access_token: token });
      }
    } catch (error) {
      console.error("Failed to refresh Google access token:", error);
      throw new Error("Google access token expired. Please re-authenticate your Google account.");
    }
  }

  return oauth2Client;
}
